In [3]:
import numpy
import math

def standardize(matrix):
	# get length and height of matrix
	length = len(matrix)
	height = len(matrix[0])
	new_matrix = matrix.copy()

	# create min and max vals for range
	min_vals = [math.inf] * length
	max_vals = [-math.inf] * length

	# loop through each row/col combo
	for row_id, row in enumerate(matrix):
		for col_id, cell in enumerate(row):
			if cell > max_vals[col_id]:
				max_vals[col_id] = cell
			if cell < min_vals[col_id]:
				min_vals[col_id] = cell

	# do it again now that we calculated stuff
	# this time we are applying new values to the output
	for row_id, row in enumerate(matrix):
		for col_id, cell in enumerate(row):
			min = min_vals[col_id]
			max = max_vals[col_id]
			# calculate the "normalized" cell value
			val = (cell - min) / (max - min)
			new_matrix[row_id][col_id] = val
	return new_matrix

my_2d_matrix = [
	[1, 20, 300],
	[2, 30, 100],
	[5,-10, 600],
]

example_matrix = [
	[1000, 2],
	[1500, 3],
]

print(standardize(example_matrix))

[[0.0, 0.0], [1.0, 1.0]]


In [4]:
import numpy

def max_min_s(x):
	return (x - x.min(axis = 0)) / (x.max(axis = 0) - x.min(axis = 0))

x_train = numpy.array([[1000., 2.], [1500., 3.]])
print(max_min_s(x_train))

[[0. 0.]
 [1. 1.]]


In [5]:
from sklearn import preprocessing as preproc

scaler = preproc.MinMaxScaler()
x_min_max = scaler.fit_transform(x_train)

print(x_min_max)

[[0. 0.]
 [1. 1.]]


## Activity 2

In [6]:
def standard_s(x):
	return (x - x.mean(axis = 0)) / (x.std(axis = 0))

x_train = numpy.array([[1000., 2.], [1500., 3.]])
print(max_min_s(x_train))

[[0. 0.]
 [1. 1.]]


In [7]:
standard_scaler = preproc.StandardScaler()

In [8]:
# ...